### ISSUE TITLE
Making the code even better

### ISSUE THREAD

**Issue by PartyManCZ** [parjosuparjo/netflix-checker#1]
Hey! I have made some changes to your code like a possibility to have a wordlist list names and passwords and changing proxy but I would like to get in contact with you if it is possible because I still dont understand some parts of it even tho I spent like 10 hours on remaking it already. So is there any possibility to get in touch with you? Thanks

Best regards,
Petr Ziegner
Instagram: @petr_ziegner
Facebook: Petr Ziegner

**Comment by DexterTech111** [comment]
i can help you

**Comment by PartyManCZ** [comment]
@DexterTech111 Thanks for responding, sadly I already abandoned that project and made it myself in python, but thanks anyways!
